return {
	scavapparition = {
		maxacc = 0.207,
		autoheal = 50,
		maxdec = 0.6486,
		energycost = 1,
		metalcost = 1,
		builddistance = 200,
		buildpic = "scavengers/SCAVMIST.DDS",
		buildtime = 5500,
		canmove = true,
		canassist = true,
		cancloak = true,
		initcloaked = true,
		decloakonfire = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "64 24 64",
		collisionvolumetype = "CylY",
		explodeas = "",
		floater = true,
		footprintx = 4,
		footprintz = 4,
		hidedamage = true,
		kamikaze = true,
		kamikazedistance = 50,
		mass = 1000,
		health = 500,
		speed = 120.0,
		maxwaterdepth = 0,
		movementclass = "HHOVER4",
		nochasecategory = "ALL",
		objectname = "scavs/scavmistflare.s3o",
		power = 500,
		radardistancejam = 300,
		script = "scavs/SCAVMIST.cob",
		seismicsignature = 0,
		selfdestructas = "",
		selfdestructcountdown = 0,
		sightdistance = 300,
		stealth = true,
		strafetoattack = true,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.5,
		turnrate = 1200,
		workertime = 200,
		unitname = "scavapparition",
		customparams = {
			juno_deny = true,
			juno_kill = true,
			model_author = "SethDGamre",
			normaltex = "unittextures/Arm_normal.dds",
			paralyzemultiplier = 0.001,
			subfolder = "Scavengers",
			inheritxpratemultiplier = 0.1,
			childreninheritxp = "BOTCANNON",
			parentsinheritxp = "BOTCANNON",
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:scavmist",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count1",
			},
			ok = {
				[1] = "spider2",
			},
			select = {
				[1] = "spider",
			},
		},
		weapondefs = {
			landunitspawner = {
				areaofeffect = 1,
				avoidfriendly = false,
				avoidground = false,
				avoidfeature = false,
				burnblow = true,
				burst = 10,
				burstrate = 0.1,
				collidefriendly = false,
				collideenemy = false,
				collideneutral = false,
				collidefeature = false,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 0.15,
				explosiongenerator = "",
				gravityaffected = "true",
				heightboostfactor = 0,
				model = "",
				name = "Teleporter",
				noselfdamage = true,
				range = 200,
				reloadtime = 60,
				rgb = 0.0,
				0.0,
				0.0,
				soundhit = "",
				soundhitwet = "",
				soundstart = "",
				sprayangle = 18000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 3000,
				customparams = {
					spawns_name = "armwar armham armrock armstump armflash armpincer armjanus corthud corstorm corlevlr corgarp corraid corgator legbal legkark legcen leglob legamphtank leggat leghelios leghades armpw corak leggob armpw corak leggob armpw corak leggob armpw corak leggob armpw corak leggob armpw corak leggob armpw corak leggob armpw corak leggob armpw corak leggob armpw corak leggob",
					spawns_surface = "LAND",
					spawns_mode = "random",
					spawns_ceg = "scav-spawnexplo-medium",
					spawns_stun = 1,
				},
				damage = {
					default = 0,
				},
			},
			landturretspawner = {
				areaofeffect = 1,
				avoidfriendly = false,
				avoidground = false,
				avoidfeature = false,
				burnblow = true,
				burst = 4,
				burstrate = 0.1,
				collidefriendly = false,
				collideenemy = false,
				collideneutral = false,
				collidefeature = false,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 0.15,
				explosiongenerator = "",
				gravityaffected = "true",
				heightboostfactor = 0,
				model = "",
				name = "Teleporter",
				noselfdamage = true,
				proximitypriority = -1,
				range = 300,
				reloadtime = 60,
				rgb = 0.0,
				0.0,
				0.0,
				soundhit = "",
				soundhitwet = "",
				soundstart = "",
				sprayangle = 18000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 3000,
				customparams = {
					spawns_name = "armbeamer armhlt armclaw armferret armrl armrl corhllt corhlt cormaw cormadsam corrl corrl legmg legdtr legrhapsis legrl legrl armllt corllt leglht armllt corllt leglht armllt corllt leglht armllt corllt leglht armllt corllt leglht",
					spawns_surface = "LAND",
					spawns_mode = "random",
					spawns_expire = 60,
					spawns_ceg = "scav-spawnexplo-medium",
					spawns_stun = 1,
				},
				damage = {
					default = 0,
				},
			},
			waterspawner = {
				areaofeffect = 1,
				avoidfriendly = false,
				avoidground = false,
				avoidfeature = false,
				burnblow = true,
				burst = 8,
				burstrate = 0.1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collideenemy = false,
				collideneutral = false,
				collidefeature = false,
				cylindertargeting = 1,
				edgeeffectiveness = 0.15,
				explosiongenerator = "",
				gravityaffected = "true",
				heightboostfactor = 0,
				model = "",
				name = "Teleporter",
				noselfdamage = true,
				proximitypriority = -1,
				range = 300,
				reloadtime = 60,
				rgb = 0.0,
				0.0,
				0.0,
				soundhit = "",
				soundhitwet = "",
				soundstart = "",
				sprayangle = 18000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 3000,
				customparams = {
					spawns_name = "armdecade armpship armsub corpship corpt armanac corsnap legner armpt coresupp armsh corsh legsh armpt coresupp armsh corsh legsh armpt coresupp armsh corsh legsh armpt coresupp armsh corsh legsh",
					spawns_surface = "SEA",
					spawns_mode = "random",
					spawns_ceg = "scav-spawnexplo-medium",
					spawns_stun = 1,
				},
				damage = {
					default = 0,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "landunitspawner",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				badtargetcategory = "VTOL UNDERWATER",
				def = "landturretspawner",
			},
			[3] = {
				badtargetcategory = "VTOL",
				def = "waterspawner",
			},
		},
	},
}
